kind: Service
apiVersion: v1
metadata:
  name: postgres-dns
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    service: select                   #selecting PODS
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80                  #LB
      targetPort: 80                  #pod
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres
