# Source: openresty-art/templates/configmap-conf.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: apache-index-configmap
  labels:
    app: apache
data:
  index.php: |
    <?php
    $dbconn = pg_connect("host=postgres port=5432 dbname=postgresdb user=admin password=psltest");
    //connect to a database named "postgres" on the host "host" with a username and password
    if (!$dbconn){
    echo "<center><h1>Doesn't work (=(</h1></center>";
    }else
    echo "<center><h1>Good connection from dns</h1></center>";
    pg_close($dbconn);
    ?>
  db.php: |
    <?php
    include '/etc/secret/postgres-username';
    $dbconn = pg_connect("host=postgres port=5432 dbname=postgresdb user=$SECRET_USERNAME password=$SECRET_PASSWORD");
    //connect to a database named "postgres" on the host "host" with a username and password
    if (!$dbconn){
    echo "<center><h1>Doesn't work from secrets(=(</h1></center>";
    }else
    echo "<center><h1>Good connection from secrets</h1></center>";
    pg_close($dbconn);




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        service: select               # from sevice
        app    : apache
    spec:
      containers:
      - name: apache
        image: ebarbat/test:latest
        ports:
        - containerPort: 80
        env:
         - name: SECRET_USERNAME
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
              optional: false # same as default; "mysecret" must exist
                              # and include a key named "username"
         - name: SECRET_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
              optional: false # same as default; "mysecret" must exist
                              # and include a key named "password"



        volumeMounts:
            - name: apache-index-file
              mountPath: /var/www/html/
      volumes:
      - name: apache-index-file
        configMap:
          name: apache-index-configmap
