name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:        
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: set release date
        run: |
            echo "time=$(date +'%Y-%m-%dT-%H-%M-%S')" >> ${GITHUB_ENV}
            
      - name: change web-write
        run: |
tee -a nginx+mysql/web-write-db.yaml <<EOF

apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-deployment
  labels:
    app: write

spec:
  replicas: 1
  selector:
    matchLabels:
      app: write
  template:
    metadata:
      labels:
        app: write
    spec:
      containers:
      - name: nginx-write
        image: ebarbat/test:$time
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        - containerPort: 443
EOF
        
      - name: Build the Docker image
        run: docker build . --file nginx+mysql/write/Dockerfile --tag ebarbat/test:$time
          
      - name: Push the Docker image
        run: docker push ebarbat/test:$time  #nginxWrite
                    


          
          

 
