name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#env:
  #tttest: (date +'%Y-%m-%dT:%H:%M:%S')
  #DAY_OF_WEEK: date +'%Y-%m-%dT:%H:%M:%S'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: set release date
        run: |
            echo "time=$(date +'%Y-%m-%dT-%H-%M-%S')" >> ${GITHUB_ENV}
#            echo "time=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
            
            
      - name: Build the Docker image
        run: docker build . --file nginx+mysql/write/Dockerfile --tag ebarbat/test:$time
  

        
      - name: Build the Docker image
        run: docker push ebarbat/test:$time  #nginxWrite
          
          
          
          

 
