name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ebarbat/test
          
      - name: Build the Docker image
        run: docker build . --file nginx+mysql/write/Dockerfile --tag ebarbat/test:nginxWrite
      - name: Docker meta
        id: meta
        #uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ebarbat/test:nginxWrite
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
      - name: Build the Docker image
        run: docker push ebarbat/test:${{ steps.meta.outputs.tags }}   #nginxWrite
          
          
          
          

 
