name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  tttest: (date +'%Y-%m-%d:%H:%M:%S')
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

          
      - name: Build the Docker image
        run: docker build . --file nginx+mysql/write/Dockerfile --tag ebarbat/test:$tttest
  

        
      - name: Build the Docker image
        run: docker push ebarbat/test:$tttest  #nginxWrite
          
          
          
          

 
