name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:        
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: set release date
        run: |
            echo "time=$(date +'%Y-%m-%dT-%H-%M-%S')" >> ${GITHUB_ENV}
            
      - name: change web-write
        run: |
            echo "apiVersion: apps/v1" > nginx+mysql/web-write-db.yaml
            echo "kind: Deployment" >> nginx+mysql/web-write-db.yaml
            echo "metadata:" >> nginx+mysql/web-write-db.yaml
            echo "  name: write-deployment" >> nginx+mysql/web-write-db.yaml
            echo "  labels:" >> nginx+mysql/web-write-db.yaml
            echo "    app: write" >> nginx+mysql/web-write-db.yaml

            echo "spec:" >> nginx+mysql/web-write-db.yaml
            echo "  replicas: 1" >> nginx+mysql/web-write-db.yaml
            echo "  selector:" >> nginx+mysql/web-write-db.yaml
            echo "    matchLabels:" >> nginx+mysql/web-write-db.yaml
            echo "      app: write" >> nginx+mysql/web-write-db.yaml
            echo "  template:" >> nginx+mysql/web-write-db.yaml
            echo "    metadata:" >> nginx+mysql/web-write-db.yaml
            echo "      labels:" >> nginx+mysql/web-write-db.yaml
            echo "        app: write" >> nginx+mysql/web-write-db.yaml
            echo "    spec:" >> nginx+mysql/web-write-db.yaml
            echo "      containers:" >> nginx+mysql/web-write-db.yaml
            echo "      - name: nginx-write" >> nginx+mysql/web-write-db.yaml
            echo "        image: ebarbat/test:$time" >> nginx+mysql/web-write-db.yaml
            echo "        imagePullPolicy: \"Always\"" >> nginx+mysql/web-write-db.yaml
            echo "        ports:" >> nginx+mysql/web-write-db.yaml
            echo "        - containerPort: 80" >> nginx+mysql/web-write-db.yaml
            echo "        - containerPort: 443 " >> nginx+mysql/web-write-db.yaml
        
      - name: Build the Docker image
        run: docker build . --file nginx+mysql/write/Dockerfile --tag ebarbat/test:$time
          
      - name: Push the Docker image
        run: docker push ebarbat/test:$time  #nginxWrite
                    


          
          

 
